### ISSUE TITLE
about readme

### ISSUE THREAD

**Issue by brunobell** [russianidiot/self.py#1]
Did you forget to add self as the first arguement in both functions of CLS class in README.md file?
And, I know this would be a very stupid question to ask but, I wonder whether this @self decorator can be used outside a class just like inside the class in your README.md file? Thanks pal.

**Comment by russianidiot** [comment]
true, thx

**Comment by russianidiot** [comment]
2: no, inside class only

**Comment by brunobell** [comment]
Thanks for your answer and plenty of shared neatly written codes :+1:
